version: '3'
services:
  app1:
    build: 
      context: ./app1
      args:
        - NODE_ENV=development
    volumes:
      - ./app1:/app1
      - /app1/node_modules

    environment:
      - NODE_ENV=development
    command: npm run dev
  app2:
    build: 
      context: ./app2
      args:
        - NODE_ENV=development
    volumes:
      - ./app2:/app2
      - /app2/node_modules

    environment:
      - NODE_ENV=development
    command: npm run dev