version: '3'
services:
  app1:
    build: 
      context: /app1
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    command: node index.js
  app2:
    build: 
      context: /app2
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    command: node index.js