version: '3'
services:
  app1:
    build:
      context: ../../app1
      dockerfile: Dockerfile-alternate
      args:
        - NODE_ENV=development
    ports:
      - "1000:1000"
    environment:
      - PORT=1000
  app2:
    build:
      context: /app2
      args:
        - NODE_ENV=development
    ports:
      - "2000:2000"
    environment:
      - PORT=2000

  mongodb:
    image: 'mongo:latest'
    ports: 
      - '27017:27017'
    expose:
      - 27017